output_dir: ./data/sim_outputs/stability_map

metric_mass_scale: 1.0
energy_check_only: false   # true = faster probe; set to false here

processes: 4
threads_per_process: 1

param1:                # x-axis
  name: mu_squared
  key: mu_squared
  start: 1.1          # ensure μ^2 > 2P over much of the grid
  stop: 2.0
  num_points: 16
  transform: linear

param2:                # y-axis
  name: P_env
  key: P_env
  start: 0.0
  stop: 0.5
  num_points: 16
  transform: linear

solver:
  mu_squared: 1.5
  P_env: 0.1
  lattice_size: [24, 24, 16, 16]
  dx: 0.5
  # fixed stabilizers (moderate, nonzero)
  g_squared: 0.2
  h_squared: 0.1
  # defaults for the rest
  lambda_val: 2.0
  seed_nw: 1
  relaxation_dt: 1.0e-5
  max_iterations: 8000
  early_exit_energy_threshold: 5.0e3
  relaxation_n_skip: 300
  relaxation_n_iter: 512
  # cautious growth
  energy_check_interval: 20      # was 5
  convergence_threshold: 0.1     # was 1e-6 (this threshold is for *power*, not relative ΔE)
  dt_up_factor: 1.002            # slower growth keeps late-time steps gentle
  friction: 0.92                 # a touch more damping helps plateau
