simulation:
  grid_size: 800
  window: [-10, 10, -10, 10]
  beta: .05            # legacy key 'G_effective' also accepted
  kappa_bar: 1.0        # legacy key 'kappa_inf' also accepted
  softening_epsilon: 1.0e-4
  clip_min: 0.0
  clip_max: 1.0
  masses:
    - { mass: 5.0,  position: [-3.5,  0.0], color: "white" }
    - { mass: 12.0, position: [ 3.0,  1.5], color: "white" }

plotting:
  dpi: 220
  figsize: [14, 10]
  cmap: "magma"
  interp: "bilinear"
  title_kappa: "GEF Time Dilation (κ/κ̄)"
  title_potential: "Wake Potential W(r)"
  facecolor: "black"
  show_masses: true
  base_marker_size: 120.0
  marker_scale: 600.0
  mass_size_exponent: 0.3333333333
  contours:
    show: true
    levels: 12
    color: "white"
    linewidth: 0.8
    alpha: 0.6
  potential_panel:
    show: true
    cmap: "viridis"
    scale: "linear"     # "log" also supported
    vmin: null          # null => use robust percentiles
    vmax: null
    clip_percentiles: [2, 98]

# Optional overall output override; otherwise SCRIPT_DIR/_outputs is used
# output_dir: "./_outputs"
