# Configuration for the GEF κ-Flow Simulator
# Describes a scene with massive objects and visualizes their effect on the local time flow rate.

simulation:
  grid_size: 2048       # Resolution of the simulation grid 
  window: [-1, 1, -1, 1] # [x_min, x_max, y_min, y_max] physical area
  
  # The effective gravitational coupling constant. This combines the GEF
  # constants α and β into a single value for visualization.
  G_effective: 0.2
  
  # A list of all massive objects in the simulation.
  masses:
    - mass: 100.0
      position: [-0.5, 0.0]  # [x, y] coordinates
      
    - mass: 30.0
      position: [0.5, 0.0]   # [x, y] coordinates
      
    - mass: 5.0
      position: [-6.0, 7.0]

output_dir: 'results/k_flow_simulations' # Use a relative path for portability

plotting:
  figsize: [20, 20]
  cmap: 'inferno' # 'magma', 'hot', 'plasma' are also great choices
  dpi: 150