# Default configuration for NW (Nambu-Wheeler) mass spectrum calculation
# This config defines parameters for the NW model and comparison with observed masses

# --- NW Model Parameters ---
nw_model:
  # Base frequency (Hz)
  base_frequency: 1.0e20
  
  # Coupling constant
  alpha: 1.0/137.036
  
  # Quantum numbers range to explore
  quantum_numbers:
    n_min: 1
    n_max: 10
    l_min: 0
    l_max: 5
    m_min: -5
    m_max: 5
  
  # Resonance parameters (similar to the resonance model in Hopfion physics)
  resonance:
    base_value: 1.0
    peaks:
      - center: 1
        amplitude: 0.5
        sigma: 0.2
      - center: 2
        amplitude: 0.3
        sigma: 0.15
      - center: 3
        amplitude: 0.2
        sigma: 0.1

# --- Analysis Settings ---
analysis:
  # Mass range to explore (MeV)
  mass_min: 0.1
  mass_max: 200000
  
  # Resolution (number of points in the spectrum)
  resolution: 10000
  
  # Matching tolerance (percentage difference for considering a match)
  match_tolerance: 0.05
  
  # Enable pattern recognition for finding mass ratios
  pattern_recognition: true
  
  # Mass ratio patterns to search for
  ratio_patterns: [2, 3, 4, 8, 16]

# --- Standard Model Comparison ---
# Observed particle masses to compare with the calculated spectrum
observed_masses:
  # Leptons
  - name: "Electron"
    mass_MeV: 0.511
    family: "leptons"
  - name: "Muon"
    mass_MeV: 105.7
    family: "leptons"
  - name: "Tau"
    mass_MeV: 1776.86
    family: "leptons"
  
  # Quarks
  - name: "Up"
    mass_MeV: 2.2
    family: "quarks"
  - name: "Down"
    mass_MeV: 4.7
    family: "quarks"
  - name: "Charm"
    mass_MeV: 1280
    family: "quarks"
  - name: "Strange"
    mass_MeV: 96
    family: "quarks"
  - name: "Top"
    mass_MeV: 173100
    family: "quarks"
  - name: "Bottom"
    mass_MeV: 4180
    family: "quarks"
  
  # Bosons
  - name: "W Boson"
    mass_MeV: 80379
    family: "bosons"
  - name: "Z Boson"
    mass_MeV: 91188
    family: "bosons"
  - name: "Higgs Boson"
    mass_MeV: 125180
    family: "bosons"

# --- Visualization Settings ---
visualization:
  # Plot types to generate
  plots:
    - type: "spectrum"
      title: "NW Model Mass Spectrum"
      x_axis: "Mass (MeV)"
      y_axis: "Spectral Density"
      log_x: true
      
    - type: "comparison"
      title: "NW Model vs Observed Masses"
      x_axis: "NW Model Mass (MeV)"
      y_axis: "Observed Mass (MeV)"
      log_x: true
      log_y: true
      
    - type: "ratio_pattern"
      title: "Mass Ratio Patterns"
      x_axis: "Mass Ratio"
      y_axis: "Frequency"
  
  # Figure size (width, height) in inches
  figsize: [12, 8]
  
  # Output DPI
  dpi: 300
