description: "Extended P sweep at moderate stiffness to locate peninsula"

# Where outputs go
output_dir: ./data/sim_outputs/stability_map

# Parallelism
processes: 0                # 0 -> auto (n_cores - 1)
threads_per_process: 2

# Sweep axes — each maps to a HopfionRelaxer config key
param1:
  name: mu_squared
  key: mu_squared
  start: 1.18
  stop: 1.32
  num_points: 8
  transform: linear

param2:
  name: P_env
  key: P_env
  start: 0.40
  stop: 1.20
  num_points: 17
  transform: linear

# Base solver config (anything not controlled by the two axes)
solver:
  lattice_size: [24, 24, 16, 16]
  dx: 0.50
  mu_squared: 1.18      # baseline; gets overridden along param1
  lambda_val: 2.0
  P_env: 0.40           # baseline; gets overridden along param2
  g_squared: 0.20
  h_squared: 0.10
  seed_topology: 1      # hopfion seed
  max_iterations: 20000
  clip_phi_to_unit: false

# Scoring and diagnostics
scoring:
  use_numeric_vacuum: true
  cache_numeric_vacuum: true
  score_ref_mass_density: 0.07
  save_top_k: 5

outputs:
  save_fields_for_top_k: true
  save_energy_breakdown: true
