mode: sweep

plotting:
  dpi: 200
  figsize: [14, 10]
  title: GEF Mass-to-Geometry Spectrometer
  xlabel: "Particle Rest Mass (MeV/c²)"   # UTF-8 superscript
  ylabel: "Predicted Reduced Compton Length λ̄ (fm)"

single_mass_MeV: 235.0

sweep:
  num_points: 10000
  scale: log
  start_MeV: 0.1
  stop_MeV: 1.0e6

known_particles:
  - { name: "Electron",      mass: 0.51099895, color: "#2ca02c" }  # green
  - { name: "Muon",          mass: 105.658,    color: "#2ca02c" }
  - { name: "Tau",           mass: 1776.86,    color: "#2ca02c" }
  - { name: "Pion (π⁺)",     mass: 139.570,    color: "#17becf" }  # cyan
  - { name: "Proton",        mass: 938.272,    color: "#17becf" }
  - { name: "W Boson",       mass: 80379,      color: "#ff7f0e" }  # orange
  - { name: "Z Boson",       mass: 91187,      color: "#ff7f0e" }
  - { name: "Higgs Boson",   mass: 125100,     color: "#d62728" }  # red
  - { name: "Top Quark",     mass: 172760,     color: "#d62728" }
  - { name: "Planck Mass",   mass: 1.22091e19, color: "#e377c2" }  # magenta
