description: "2D sweep: move window to crest (expand P down, mu^2 up)"

# Where outputs go
output_dir: ./data/sim_outputs/stability_map

# Parallelism
processes: 0                # 0 -> auto (n_cores - 1)
threads_per_process: 2

# step-1b: move the window to the crest
param1:
  name: P_env
  key: P_env
  start: 0.40
  stop: 0.53
  num_points: 21
  transform: linear

param2:
  name: mu_squared
  key: mu_squared
  start: 1.12
  stop: 1.32
  num_points: 21
  transform: linear

# Base solver config
solver:
  lattice_size: [24, 24, 16, 16]
  dx: 0.50
  mu_squared: 1.12          # baseline; overridden along param2
  lambda_val: 2.0
  P_env: 0.40               # baseline; overridden along param1
  g_squared: 0.20
  h_squared: 0.10
  seed_topology: 1
  max_iterations: 20000
  clip_phi_to_unit: false
  relaxation_n_skip: 0
  relaxation_n_iter: 20000

# Scoring and diagnostics
scoring:
  use_numeric_vacuum: true
  cache_numeric_vacuum: true
  score_ref_mass_density: 0.07
  density_normalization: "4D"
