description: "1D micro-sweep around mu^2* at fixed P* (spacing <= 0.001 over ±0.03)"

# Where outputs go
output_dir: ./data/sim_outputs/stability_map

# Parallelism
processes: 0                # 0 -> auto (n_cores - 1)
threads_per_process: 2

# NOTE: Replace P_STAR and MU2_STAR with the 2D argmax values
param1:
  name: mu_squared
  key: mu_squared
  start: MU2_STAR - 0.03
  stop:  MU2_STAR + 0.03
  num_points: 61            # step ~0.001
  transform: linear

param2:
  name: P_env
  key: P_env
  start: P_STAR
  stop: P_STAR
  num_points: 1
  transform: linear

# Base solver config
solver:
  lattice_size: [24, 24, 16, 16]
  dx: 0.50
  mu_squared: MU2_STAR
  lambda_val: 2.0
  P_env: P_STAR
  g_squared: 0.20
  h_squared: 0.10
  seed_topology: 1
  max_iterations: 20000
  clip_phi_to_unit: false
  relaxation_n_skip: 0
  relaxation_n_iter: 20000

# Scoring and diagnostics
scoring:
  use_numeric_vacuum: true
  cache_numeric_vacuum: true
  score_ref_mass_density: 0.07
  density_normalization: "4D"
