description: "1D sharp sweep around boundary (P_env) at fixed mu^2=1.26"

# Where outputs go
output_dir: ./data/sim_outputs/stability_map

# Parallelism
processes: 0                # 0 -> auto (n_cores - 1)
threads_per_process: 2

# Sweep axes — ultra-fine around P*
param1:
  name: P_env
  key: P_env
  start: 0.58
  stop: 0.68
  num_points: 201          # step ≈ 0.0005 across 0.10 window
  transform: linear

# Keep mu^2 fixed via 1-point second axis
param2:
  name: mu_squared
  key: mu_squared
  start: 1.26
  stop: 1.26
  num_points: 1
  transform: linear

# Base solver config
solver:
  lattice_size: [24, 24, 16, 16]
  dx: 0.50
  mu_squared: 1.26
  lambda_val: 2.0
  P_env: 0.58
  g_squared: 0.20
  h_squared: 0.10
  seed_topology: 1
  max_iterations: 20000      # align with relaxation_n_iter
  clip_phi_to_unit: false
  relaxation_n_skip: 0
  relaxation_n_iter: 20000

# Scoring and diagnostics
scoring:
  use_numeric_vacuum: true
  cache_numeric_vacuum: true
  score_ref_mass_density: 0.07
  density_normalization: "4D"
