description: "1D mu^2 ridge trace at fixed P_env ~ P* (Δmu^2≈0.0015)"

# Where outputs go
output_dir: ./data/sim_outputs/stability_map

# Parallelism
processes: 0                # 0 -> auto (n_cores - 1)
threads_per_process: 2

# Sweep axes — mu^2 fine sweep; fix P_env at best P*
# NOTE: Replace the placeholder P_env value below with your measured P* from the micro sweep.
param1:
  name: mu_squared
  key: mu_squared
  start: 1.20
  stop: 1.32
  num_points: 81            # step ≈ (1.32-1.20)/(81-1) = 0.0015
  transform: linear

param2:
  name: P_env
  key: P_env
  start: 0.507
  stop: 0.507
  num_points: 1
  transform: linear

# Base solver config
solver:
  lattice_size: [24, 24, 16, 16]
  dx: 0.50
  mu_squared: 1.20          # baseline; overridden along param1
  lambda_val: 2.0
  P_env: 0.507
  g_squared: 0.20
  h_squared: 0.10
  seed_topology: 1
  max_iterations: 20000
  clip_phi_to_unit: false
  relaxation_n_skip: 0
  relaxation_n_iter: 20000

# Scoring and diagnostics
scoring:
  use_numeric_vacuum: true
  cache_numeric_vacuum: true
  score_ref_mass_density: 0.07
  density_normalization: "4D"
