# Configuration for the GEF "Quantize Gravity" Simulation
# This experiment simulates the co-evolution of local geometry and physical
# laws to search for a stable, self-consistent "Genesis Configuration."

# OTHER MODES:
# mode: 'quantize-gravity'
# mode: 'julia'
# mode: 'mandelbrot'
# mode: 'orbit'
mode: 'quantize-gravity'


genesis_sweep_params:
  # The parameter within 'quantize_gravity_params' to animate.
  # Common choices: 'genesis_target' or 'genesis_strength'
  parameter_to_sweep: 'genesis_strength'

  # --- Sweep Parameters ---
  start_angle_pi: 0.0
  end_angle_pi: 2.0 
  num_frames: 50


  # The range of values for the sweep.
  start_value: 0
  end_value: 3
  
# --- Genesis Fixed Parameters: The non-swept parameters for the simulation ---
quantize_gravity_params:
  # If 'genesis_target' is being swept, this value is ignored.
  # If another param is swept, this is the fixed target value.
  genesis_target: 0.4
  
  # The strength of the gravity-law coupling.
  genesis_strength: 0.75
  
  # Damping factor for the Îº-flow grid's "memory".
  k_damping: 0.8
  
  # The fixed misalignment angle for this simulation.
  fixed_angle_pi: 0.25
  
  # Whether to run in Julia mode (True) or Mandelbrot mode (False)
  is_julia: false

# --- Shared Parameters ---
julia_set_c: [-0.6, 0.8] # Only used if is_julia is true

anisotropy_scaling:
  x: 1.0 # The x-scaling remains constant

# --- Simulation & Render Quality ---
image_size: 512 # Keep this lower for faster testing of animations
max_iterations: 300
fractal_window: [-2.0, 2.0, -2.0, 2.0]

# --- Output & Plotting ---
output_dir: '/Volumes/VFX/GEF/data/analysis/fractal_spelunker_v2'
plotting:
  animation_figsize: [12, 12]
  cmap: 'magma'
  dpi: 100
  normalization: 'relative' 