# --- Experiment Metadata ---
particle_type: "LeptonFamily"
output_dir: "data/sim_outputs/mass_spectrum/"

# --- Physical Parameters of the GEF Lagrangian ---
# NOTE: These parameters result in a symmetric vacuum at phi=0 because mu_squared <= 2*P_env.
# This is a valid physical regime, but not a broken-symmetry "Mexican Hat" phase.
mu_squared: 1.0
lambda_val: 2.0
P_env: 0.5
h_squared: 0.0 # Hook term is disabled

# --- Resonance Model ---
# NOTE: The amplitudes have been adjusted to weaken, but not eliminate, the g_squared term.
# The previous values (e.g., -5.0) would have been clamped to 0.0 by the safety guard.
resonance_parameters:
  g_base_squared: 0.1
  invert_amplitudes: false
  peaks:
    - center: 207
      amplitude: -0.08  # Results in g_eff_sq = 0.02 at the peak
      sigma: 5.0
      type: "gaussian" # Explicitly state the type for clarity
    - center: 3477
      amplitude: -0.05  # Results in g_eff_sq = 0.05 at the peak
      sigma: 20.0
      type: "gaussian"

# --- Simulation Grid & Solver Parameters ---
lattice_size: [32, 32, 32, 32]
dx: 0.5

# --- Integrator & Convergence Parameters ---
relaxation_dt: 1.0e-5
max_iterations: 30000  # Increased slightly to accommodate a stricter threshold
convergence_threshold: 1.0e-6 # Tightened for more accurate energy minima
early_exit_energy_threshold: 5000.0
friction: 0.80

# --- Experiment Sweep Configuration ---
processes: 6
relaxation_n_skip: 500
relaxation_n_iter: 1024
nw_sweep_range: [1, 100, 207, 500, 1000, 3000, 3477, 4000, 5000]