# Master Configuration for the GEF Lepton Mass Hierarchy Calibration

# --- Experiment Metadata ---
particle_type: "CalibratedLeptonFamily"
output_dir: "data/sim_outputs/calibration_runs/"

# --- Calibration Target: The Ground Truth from Our Universe ---
calibration_target:
  # We now target the ratio of the two higher generations, as it's the cleanest signal
  muon_mass_MeV: 105.66
  tau_mass_MeV: 1776.86
  tau_to_muon_mass_ratio: 16.816 # 1776.86 / 105.66

objective:
  mode: integrated_ratio
  use_log_error: true  # optional

# --- Fixed Physical Parameters of the GEF Lagrangian ---
# These are the "laws of nature" we are assuming for this run.
# They are anchored by other parts of the GEF theory.
mu_squared: 1.0
lambda_val: 1.152  # Anchored by the fine-structure constant prediction
P_env: 0.01
h_squared: 0.0     # No self-interaction for single leptons

# --- Optimization Parameters: The "Dials" to be Tuned ---
optimization_params:
  max_iterations: 50
  # Integration width factors (in units of sigma) for the mass calculation
  muon_integration_width_factor: 6.0
  tau_integration_width_factor: 6.0
  # If true, saves a CSV for each optimizer step. Useful for debugging, but can be slow.
  save_csv_during_opt: true
  parameter_info:
    - name: "muon_amplitude"
      initial: -2.5
      min: -10.0
      max: -0.1
      config_path: "resonance_parameters.peaks[0].amplitude"
    - name: "muon_sigma"
      initial: 10.0
      min: 1.0
      max: 30.0
      config_path: "resonance_parameters.peaks[0].sigma"
    - name: "tau_amplitude"
      initial: -1.0
      min: -10.0
      max: -0.1
      config_path: "resonance_parameters.peaks[1].amplitude"
    - name: "tau_sigma"
      initial: 50.0
      min: 10.0
      max: 200.0
      config_path: "resonance_parameters.peaks[1].sigma"

# --- Resonance Model (Structure) ---
# The optimizer will fill in the 'amplitude' and 'sigma' values.
resonance_parameters:
  g_base_squared: 0.1
  peaks:
    - center: 206.77  # Center the peak on the target ratio
      amplitude: -2.5 # This is the initial guess
      sigma: 5.0      # This is the initial guess
    - center: 3477.2  # Center the peak on the target ratio
      amplitude: -1.0 # This is the initial guess
      sigma: 20.0     # This is the initial guess

# --- Simulation Grid & Solver Parameters (for each trial run) ---
lattice_size: [32, 32, 32, 32]
dx: 0.5
relaxation_dt: 1.0e-4
max_iterations: 10000
convergence_threshold: 1.0e-7
early_exit_energy_threshold: 1000.0
friction: 0.95
vacuum_energy: 0.0 # Should be pre-calculated for these physics params

processes: 1
threads_per_process: 6
numba_threading_layer: tbb
relaxation_n_iter: 256
relaxation_n_skip: 500

# --- Sweep Configuration (for each trial run) ---
# Use a sparse "locator" sweep to be fast during optimization.
nw_sweep_range:
  # Baseline points
  - 1
  - 2
  - 5
  - 10
  - 50
  - 100
  # Dense scan across the entire Muon valley
  - 150
  - 160
  - 170
  - 180
  - 190
  - 200
  - 205
  - 207
  - 210
  - 215
  - 220
  - 230
  - 240
  - 250
  # Sparse scan between peaks
  - 1000
  - 2000
  - 3000
  # Dense scan across the entire Tau valley
  - 3200
  - 3300
  - 3400
  - 3450
  - 3477
  - 3500
  - 3550
  - 3600
  - 3700
  # Final baseline point
  - 4000

  
