# --- Experiment Metadata ---
particle_type: "LeptonFamily"
output_dir: "data/sim_outputs/mass_spectrum/"

# --- Physical Parameters of the GEF Lagrangian ---
# These create a universe with strong confining forces, which is what we want.
mu_squared: 1.0
lambda_val: 2.0
P_env: 0.5
h_squared: 0.0

# --- Resonance Model ---
resonance_parameters:
  g_base_squared: 0.1
  invert_amplitudes: false
  peaks:
    - center: 207
      amplitude: -5.0
      sigma: 5.0
    - center: 3477
      amplitude: -2.0
      sigma: 20.0

# --- Simulation Grid & Solver Parameters ---
lattice_size: [32, 32, 32, 32]
dx: 0.5

# --- CRITICAL FIXES FOR NUMERICAL STABILITY ---
relaxation_dt: 1.0e-5        # Was 1.0e-4. Start with a smaller, more cautious timestep.
max_iterations: 20000
convergence_threshold: 1.0e-4
early_exit_energy_threshold: 5000.0
friction: 0.80               # Was 0.95. Reduce momentum to prevent runaway acceleration.

# --- Experiment Sweep Configuration ---
processes: 6
relaxation_n_skip: 500
relaxation_n_iter: 1024
nw_sweep_range: [1, 100, 207, 500, 1000, 3000, 3477, 4000, 5000]

vacuum_energy: 0.0