# Configuration for a GEF Mass Spectrum Sweep (v2 - Stability Focused)

# --- Experiment Metadata ---
particle_type: "LeptonFamily"
output_dir: "data/sim_outputs/mass_spectrum/"

# --- Physical Parameters of the GEF Lagrangian ---
mu_squared: 1.0
lambda_val: 2.0
# --- CRITICAL CHANGE: INCREASED CONFINEMENT ---
P_env: 0.5               # Was 0.01. Let's increase this by 50x to provide confinement.
h_squared: 0.0

# --- Resonance Model ---
resonance_parameters:
  g_base_squared: 0.1
  invert_amplitudes: false
  
  # Indented correctly AND with negative amplitudes for stability valleys
  peaks:
    - center: 207
      amplitude: -5.0   # Was -2.6. Let's make the well deeper.
      sigma: 5.0        # Make the well a bit wider to help catch the particle.
    - center: 3477
      amplitude: -2.0   # Was -1.1. Deeper well.
      sigma: 20.0       # Wider well.

# --- Simulation Grid & Solver Parameters ---
lattice_size: [32, 32, 32, 32]
dx: 0.5
relaxation_dt: 1.0e-4
max_iterations: 20000
convergence_threshold: 1.0e-8
early_exit_energy_threshold: 1000.0 # Increased threshold to allow for settling
friction: 0.95

# --- Experiment Sweep Configuration ---
processes: 6
relaxation_n_skip: 500
relaxation_n_iter: 1024
# Let's use a simpler, sparser sweep just to see if we get ANY stable points first.
nw_sweep_range: [1, 100, 207, 500, 1000, 3000, 3477, 4000, 5000]

vacuum_energy: 0.0