description: "Vindication Round 2A — Fine box around Golden Point (Model B target ρ≈0.5)"
output_dir: ./data/sim_outputs/vindication_round2A
processes: 0
threads_per_process: 2

param1:
  name: mu_squared
  key: mu_squared
  start: 2.90
  stop: 3.10
  num_points: 21     # ~0.01 steps
  transform: linear

param2:
  name: P_env
  key: P_env
  start: 0.66
  stop: 0.72
  num_points: 19     # ~0.0033 steps
  transform: linear

solver:
  lattice_size: [32, 32, 20, 20]   # bump fidelity
  dx: 0.5
  mu_squared: 3.0        # seed; swept by param grid
  P_env: 0.6875          # seed; swept by param grid
  lambda_val: 1.152
  g_squared: 0.10
  h_squared: 0.05
  seed_topology: 1
  max_iterations: 50000
  clip_phi_to_unit: false

scoring:
  use_numeric_vacuum: true
  cache_numeric_vacuum: true
  score_ref_mass_density: 0.5       # Model B target
  density_normalization: 4D
  require_converged: true
  max_last_update: 1e-6
