description: "Recalibration Summit Run to find the true Electron ground state (ρ≈0.0011)"
output_dir: ./data/sim_outputs/summit_recalibration
processes: 0
threads_per_process: 2

param1:
  name: mu_squared
  key: mu_squared
  # We are searching for a value of mu^2 slightly above 2P
  start: 1.40
  stop: 1.60
  num_points: 21
  transform: linear

param2:
  # Let's sweep a stabilizer to see its effect on mass
  name: g_squared
  key: g_squared
  start: 0.05
  stop: 0.15
  num_points: 11
  transform: linear

solver:
  lattice_size: [32, 32, 20, 20]
  dx: 0.5
  lambda_val: 1.152
  h_squared: 0.05
  mu_squared: 1000.40
  # --- Key Change: Fix P_env to a stable value ---
  # With P=0.7, our constraint is mu^2 <= 1.152 + 1.4 = 2.552.
  # Our sweep from 1.4 to 1.6 is well within this stable region.
  P_env: 0.70
  seed_topology: 1
  max_iterations: 75000
  convergence_threshold: 1e-9

scoring:
  use_numeric_vacuum: true
  cache_numeric_vacuum: true