description: "Confinement Search (High mu^2): Sweep g_squared × P_env with mu_squared=3.0, starting P_env high enough to keep |phi0|<=1"
output_dir: ./data/sim_outputs/confinement_search_mu2_3p0_highP
processes: 0
threads_per_process: 2

param1:
  name: g_squared
  key: g_squared
  start: 0.10
  stop: 1.00
  num_points: 10
  transform: linear

param2:
  name: P_env
  key: P_env
  # For mu^2=3.0 and lambda=1.152, require P >= (mu^2 - lambda)/2 ≈ 0.924
  start: 0.95
  stop: 1.50
  num_points: 12
  transform: linear

solver:
  lattice_size: [48, 48, 30, 30]
  dx: 0.5

  mu_squared: 3.0
  # Seed values (swept during evaluation)
  P_env: 1.0
  g_squared: 0.1

  lambda_val: 1.152
  h_squared: 0.1

  seed_topology: 1
  max_iterations: 100000
  convergence_threshold: 1e-9

scoring:
  use_numeric_vacuum: true
  cache_numeric_vacuum: true
