description: "Step 2: Find the first overtone (Muon) by perturbing the Electron."
output_dir: ./data/sim_outputs/excitation_chain

# --- Key change: Define the input state ---
input_state_path: ./data/sim_outputs/excitation_chain/step_1_final_state.npz

solver:
  # The solver config should be identical to Step 1 to ensure we're finding
  # a new resonant mode in the *same* physical universe.
  lattice_size: [64, 64, 40, 40]
  dx: 0.5
  mu_squared: 1.405
  P_env: 0.69666666
  lambda_val: 1.152
  g_squared: 0.005
  h_squared: 0.005
  max_iterations: 150000
  convergence_threshold: 1e-10


# In config_step2_muon.yml
perturbation:
  amplitude: 0.5 # Start with a strong punch
  mode_shape: "gaussian_punch" # Use the new mode
  width: 4.0 # Optional: control the size of the punch