description: "Step 1: Find the ground state (Electron) at the 'Golden Point'."
output_dir: ./data/sim_outputs/excitation_chain
processes: 0 # Use all available cores
threads_per_process: 2

# This config has no parameter sweeps. It runs a single simulation.
solver:
  lattice_size: [32, 32, 20, 20]
  dx: 0.5
  # --- The Golden Point Parameters ---
  mu_squared: 3.0
  P_env: 0.6875
  lambda_val: 1.152
  g_squared: 0.10
  h_squared: 0.05
  # --- Simulation Controls ---
  seed_topology: 1
  max_iterations: 75000  # Give it ample time to settle
  convergence_threshold: 1e-9 # Stricter convergence for the ground state
  
# We don't need the scoring section for this single run.