description: "Step 1: Find the ground state (Electron) at the 'Golden Point'."
output_dir: ./data/sim_outputs/excitation_chain
processes: 0 # Use all available cores
threads_per_process: 2

# This config has no parameter sweeps. It runs a single simulation.
solver:
  lattice_size: [64, 64, 40, 40]
  dx: 0.5
  # --- The Golden Point Parameters ---
  mu_squared: 1.405
  P_env: 0.69666666
  lambda_val: 1.152
  g_squared: 0.005
  h_squared: 0.005
  # --- Simulation Controls ---
  seed_topology: 1
  max_iterations: 150000  # Give it ample time to settle
  convergence_threshold: 1e-10 # Stricter convergence for the ground state
  
