description: "Step 3: Find the second overtone (Tau) by perturbing the Muon."
output_dir: ./data/sim_outputs/excitation_chain

# --- Load the state from the previous step ---
input_state_path: ./data/sim_outputs/excitation_chain/step_2_final_state.npz

solver:
  # Identical physical universe
  lattice_size: [32, 32, 20, 20]
  dx: 0.5
  mu_squared: 3.0
  P_env: 1.5
  lambda_val: 1.152
  g_squared: 0.10
  h_squared: 0.05
  max_iterations: 75000
  convergence_threshold: 1e-9

perturbation:
  # You might need a slightly different amplitude to kick it into the next mode.
  amplitude: 5.0e-3
  mode_shape: "symmetric_breathing"