# ──────────────────────────────────────────────────────────────────────────────
# SELECT: 
# mode: "single"
mode: "sweep"

single:
  mass_MeV: 200.0

sweep:
  start_MeV: 190.0
  stop_MeV: 200.0
  step_MeV: 1.0
